# Staging Environment Config
env=staging
parallel=true
threads=10
suiteName=AutomationSuite_Staging
appUrl=https://staging.example.com/
overrideReport=true
runTests=
runTags=smoke,sanity,regression
timeout=15
browserName=chrome
screenshotsFolder=screenshots
test_type=fe
