# Production Environment Config
env=prod
parallel=true
threads=5
suiteName=AutomationSuite_Prod
appUrl=https://production.example.com/
overrideReport=false
runTests=
runTags=smoke
timeout=20
browserName=chrome
screenshotsFolder=screenshots
test_type=fe
